// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte.dto;

import it.bz.tis.alpenstaedte.dto.OrganisazionDto;

privileged aspect OrganisazionDto_Roo_JavaBean {
    
    public String OrganisazionDto.getName() {
        return this.name;
    }
    
    public void OrganisazionDto.setName(String name) {
        this.name = name;
    }
    
}
