// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte.dto;

import it.bz.tis.alpenstaedte.dto.ResponseObject;

privileged aspect ResponseObject_Roo_JavaBean {
    
    public Object ResponseObject.getData() {
        return this.data;
    }
    
    public void ResponseObject.setData(Object data) {
        this.data = data;
    }
    
}
