// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte.dto;

import it.bz.tis.alpenstaedte.dto.UserDto;

privileged aspect UserDto_Roo_JavaBean {
    
    public String UserDto.getEmail() {
        return this.email;
    }
    
    public void UserDto.setEmail(String email) {
        this.email = email;
    }
    
}
