// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte;

import it.bz.tis.alpenstaedte.Organisazion;

privileged aspect Organisazion_Roo_JavaBean {
    
    public String Organisazion.getName() {
        return this.name;
    }
    
    public void Organisazion.setName(String name) {
        this.name = name;
    }
    
}
