// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte;

import it.bz.tis.alpenstaedte.PipUser;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PipUser_Roo_Configurable {
    
    declare @type: PipUser: @Configurable;
    
}
