// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package it.bz.tis.alpenstaedte;

import it.bz.tis.alpenstaedte.Topic;

privileged aspect Topic_Roo_JavaBean {
    
    public String Topic.getName() {
        return this.name;
    }
    
    public void Topic.setName(String name) {
        this.name = name;
    }
    
}
